packages:
  - docs
  - packages/*
  - playgrounds/*

catalogs:
  biome:
    '@biomejs/biome': 2.4.9
  build:
    '@arethetypeswrong/core': 0.18.2
    publint: 0.3.18
    tsdown: 0.21.6
    unplugin-unused: 0.5.7
  eslint:
    '@virtual-live-lab/eslint-config': 2.3.1
    eslint: 9.31.0
    typescript-eslint: 8.57.2
  node:
    '@types/node': 25.5.0
  test:
    fs-fixture: 2.8.1
    vitest: 4.1.2
  typescript:
    '@virtual-live-lab/tsconfig': 2.1.21
    typescript: 6.0.2

onlyBuiltDependencies:
  - esbuild
  - sharp
