packages:
  - docs
  - packages/*
  - playgrounds/*

catalogs:
  biome:
    '@biomejs/biome': 2.4.9
  build:
    '@arethetypeswrong/core': 0.18.2
    publint: 0.3.18
    tsdown: 0.22.3
    unplugin-unused: 0.5.7
  dev:
    '@astrojs/node': 11.0.0-beta.2
    astro: 7.0.0-beta.6
    vite: 8.0.16
  dev-astro6:
    '@astrojs/node': 10.1.4
    astro: 6.4.8
  eslint:
    '@virtual-live-lab/eslint-config': 2.3.1
    eslint: 9.31.0
    typescript-eslint: 8.57.2
  node:
    '@types/node': 25.5.0
  test:
    fs-fixture: 2.8.1
    vitest: 4.1.9
  typescript:
    '@virtual-live-lab/tsconfig': 2.1.21
    typescript: 6.0.2

onlyBuiltDependencies:
  - esbuild
  - sharp
